### ISSUE TITLE
error~~

### ISSUE THREAD

**Issue by chong1227** [flowecommerce/magento2-pt_br#1]
Problem 1
    - Installation request for flowecommerce/pt_br ^100.0 -> satisfiable by flowecommerce/pt_br[100.0.1].
    - Conclusion: remove magento/framework 100.1.0
    - Conclusion: don't install magento/framework 100.1.0
    - flowecommerce/pt_br 100.0.1 requires magento/framework 100.0.\* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.0, 100.0.2].
    - Can only install one of: magento/framework[100.1.0, 100.0.3].
    - Can only install one of: magento/framework[100.1.0, 100.0.4].
    - Can only install one of: magento/framework[100.1.0, 100.0.5].
    - Can only install one of: magento/framework[100.1.0, 100.0.6].
    - Can only install one of: magento/framework[100.1.0, 100.0.7].
    - Can only install one of: magento/framework[100.1.0, 100.0.8].
    - Can only install one of: magento/framework[100.1.0, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.0) -> satisfiable by magento/framework[100.1.0].

**Comment by gabrielqs** [comment]
Should be fixed after PR #4 was merged. Please reopen if your problem persists.
